### ISSUE TITLE
Upgrade to support laravel-elixir ^3.0.0

### ISSUE THREAD

**Issue by anderssonola** [codezero-be/laravel-elixir-icons#1]
I've upgraded to laravel-elixir 3.0.1 and the icon generation stopped working. 
https://github.com/laravel/elixir/releases/tag/3.0.0

from console: 
**\node_modules\laravel-elixir-icons\index.js:50 this.registerWatcher("icons", options.srcDir + "*.svg");**

**Comment by ivanvermeyen** [comment]
I'll look into it asap :)

**Comment by anderssonola** [comment]
Great, let me know if I can assist you in any way ...

**Comment by ivanvermeyen** [comment]
Hi,

Could you verify if everything works correctly on your end?

Please note that I've made a few changes in the options to be a bit more Elixir-like:

```
mix.icons({
    iconsPath: "assets/icons/",
    sassPath: "assets/sass/",
    fontPath: "public/fonts/",
    relativeCssDir: "/fonts/",
    iconFontName: "icon-font",
    template: "path/to/custom-icon-font-template.scss"
});
```

By default it will use the Laravel paths (resources/assets).

**Comment by anderssonola** [comment]
Tnxs for the quick fixes!

However something seems to be wrong with the paths ? 

default sass path becomes, "resources/assetsicons/"

**Comment by ivanvermeyen** [comment]
Woops :) I've added the missing slash now :)

**Comment by anderssonola** [comment]
Great works like a charm :-)
