### ISSUE TITLE
sass file path

### ISSUE THREAD

**Issue by Malin88** [codezero-be/laravel-elixir-icons#3]
Hi,
how can i change direcotry where my _icon-font.scss saved ?
Now, is always **/public/resources/assets/sass/** but I want to change this path to **/resources/scss** where all my scss files are.

**Comment by ivanvermeyen** [comment]
Hi,

You should be able to change the target SCSS path with the `sassPath` option:

```
sassPath: "resources/scss/",
```

**Comment by Malin88** [comment]
Yes, I tried this but still my root directory, surprisingly, is /public so my path looks like **/public/resources/scss/_icon-font.scss** :/

**Comment by ivanvermeyen** [comment]
Are you using the latest Elixir?
I'm using:

```
  "devDependencies": {
    "gulp": "^3.8.8",
    "laravel-elixir": "^5.0.0",
    "laravel-elixir-icons": "^2.0.3"
  }
```

**Comment by Malin88** [comment]
`
"gulp": "^3.9.1",
"laravel-elixir": "^5.0.0",
"laravel-elixir-icons": "^2.0.4",
`

but... my laravel-elixir version is still 4.2.1 and I can`t get v5 :/

**Comment by ivanvermeyen** [comment]
Sorry for the delay...

I upgraded the dependencies in my Laravel project to:
`"gulp": "^3.9.1", "laravel-elixir": "^5.0.0", "laravel-elixir-icons": "^2.0.4"`
and successfully saved to `resources/scss/`.

```
    mix.icons({
        iconsPath: assetsPath + "/icons/",
        sassPath: "resources/scss/",
        fontPath: "public/fonts/",
        relativeCssDir: "/fonts/",
        iconFontName: "icon-font",
        sassFileName: "_icon-font.scss"
    });
```

Then I reverted to `"laravel-elixir": "^4.2.1"`and I could still save it to that location...

Are you running `gulp` from the root of your project?

**Comment by Malin88** [comment]
It is very strange... Perhaps the problem is in elixir config like config.assetsDir or sth. However when I add **./** before path, everything began to work correctly.

Thanks for your help and your time!

**Comment by ivanvermeyen** [comment]
Strange indeed... I'm glad it's working now though. :+1:
